---
- name: Create NZBHydra2 Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nzbhydra2_data_directory }}"

- name: NZBHydra2
  docker_container:
    name: nzbhydra2
    image: linuxserver/nzbhydra2
    pull: true
    volumes:
      - "{{ nzbhydra2_data_directory }}:/config:rw"
    ports:
      - "5076:5076"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ nzbhydra2_user_id }}"
      PGID: "{{ nzbhydra2_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ nzbhydra2_available_externally }}"
      traefik.http.routers.nzbhydra2.rule: "Host(`{{ nzbhydra2_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.nzbhydra2.tls.certresolver: "letsencrypt"
      traefik.http.routers.nzbhydra2.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.nzbhydra2.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.nzbhydra2.loadbalancer.server.port: "5076"
      traefik.port: "5076"
